### ISSUE TITLE
Breaks with full screen add-on

### ISSUE THREAD

**Issue by MightyW0lf** [jerryzhou196/seepreviousratings#1]
When entering full screen (using [this](https://ankiweb.net/shared/info/1049863218) add-on), the UI element breaks:

![image](https://user-images.githubusercontent.com/30864557/127734376-875c8dda-4a9f-4e90-8cf2-843c2d5650f1.png)

**Comment by xygn** [comment]
Change the _init_.py file to the one below and test.

https://raw.githubusercontent.com/xygn/seepreviousratings/NDFS/__init__.py

The reason for this behaviour is `gui_hooks.state_did_change.append(setUpLegend)` is non-functional on full screen for some reason

The legend-style element is not being appended into the head tag.

Instead I migrated it to `gui_hooks.reviewer_did_show_answer.append(init)`

I'm assuming since it's just appending the style tag into head, I believe functionality is the same.


![image](https://user-images.githubusercontent.com/63365609/127745237-3100f68f-7b70-4172-9be0-e151e1bfa1bf.png)

**Comment by jerryzhou196** [comment]
Hi @MightyW0lf, thank you so much for bringing up the issue! @xygn Thank you for going above and beyond by leaving a solution. I have implemented your solution into the Ankiweb Addon and it should work now with the addon. Just click the "check for updates" button in the Anki Addon Tab.

**Comment by xygn** [comment]
@jerryzhou196 haha no worries, it's a really powerful add-on and I'm glad I could help!

Another improvement I suggest:

`def unInit(card):
    mw.reviewer.web.eval("""
      (function () {
        $("#legend-container").remove()
        $("#legend-style").remove("style");
        })()
    """)`
    
  I think this would be a better implementation for uninit function as we're appending the container over and over into the body, leaving empty div elements lurking in the body.
  
 Removing the style id legend-style also has the same effect, as given on every init, we are appending style over and over into the head. Functionally this makes no difference,  however it is just redundant to have the same style id multiple times

**Comment by jerryzhou196** [comment]
Updated the addon code with your feature. Should be out soon!
